### ISSUE TITLE
Create CS:GO port

### ISSUE THREAD

**Issue by iabarca** [iabarca/lawena-recording-tool#47]
Support for CS:GO is already present in the ``v4.x/snapshot`` update branch. We are still testing it behaves as expected. Additional features will be added after stability is consistent.

Can be downloaded from: https://www.dropbox.com/s/qbf8oj3301nknhr/lawena-snapshot-4.2.0-pre.2-60-g0ae61d9.zip?dl=0

Roadmap to basic functionality:
- [x] Determine the minimum commands required to record.
- [x] Discover what convars work differently in the recording process.
- [x] Build a list of static cvars: Stuff that _everyone_ would want enabled when recording frames.
- [x] Create list of user-selectable cvars: Stuff that a user might want enabled or disabled. Add those as options within the user interface
- [x] Increase the quality using a modified graphic config
- [x] Create user interface elements for CS:GO mode
- [x] Publish a test build
- [x] Verify build and validate it with user feedback
- [x] Minor fixes and enhancements
- [x] Verify basic recording operations (video-only and audio-only passes)

Future: Further integration with SrcDemo2/VirtualDub/HandBrake for recorded frame segments will be worked on both TF2 and CS:GO after basic functionality is working.

**Comment by iabarca** [comment]
Alright, it's possible to test stuff with this working version: [lawena-snapshot-4.2.0-pre.2-34](https://www.dropbox.com/s/rl362z0x0uklkih/lawena-snapshot-4.2.0-pre.2-34-g713ab0b.zip?dl=0)

It contains the core features, now your feedback is required. Commit details are at #48 

Instructions: extract, run ``lawena.exe`` and select Counter-Strike: Global Offensive. 

Thanks @Dubbled, @SAS41 and @shaunidiot so far.

**Comment by Dubbled** [comment]
I believe ```mat_postprocess_enable 0```` should be added as well.

**Comment by Dubbled** [comment]
![Uploading vlcsnap-2015-01-01-04h19m52s173.png . . .](Screenshot of final render.) This render is H.264 quality 10 in Handbrake with the command ```mat_postprocess_enable``` set to 0.

![Uploading vlcsnap-2015-01-01-04h24m14s27.png . . .](Screenshot of regularly recorded footage.)

**Comment by iabarca** [comment]
Ok, that can be added directly to ``recording.cfg`` inside ``lwrt/csgo/config/cfg`` ([link](https://github.com/iabarca/lawena-recording-tool/blob/csgo-support/lwrt/csgo/config/cfg/recording.cfg)). No need to bundle it in a commit yet.

**Comment by iabarca** [comment]
I've been reading [this thread](http://www.reddit.com/r/GlobalOffensive/comments/2r0zkg/as_requested_ultimate_csgo_moviemaking_guide_by/) and applied some convars and settings to the pull request before I merged it. Files/settings are loaded correctly, but I need to test the values if they are having any effect.

Other things I've learned..
* HLAE is popular between fragvideo enthusiasts.
* Lots of graphical convars are missing, are they locked? Does HLAE contribute unlocking them?
* `host_timescale 0` used in that guide, stops sounds completely.
* In TF2 you set `host_timescale 0.001` to help Source Recorder capture all needed frames (when you use high fps or have low specs) and not lose quality. However in CS:GO looks like you have to use `demo_timescale` to do that. Will test.
* The real help will come when the TGA compiling is automated or integrated in the process, like Source Recording Tool does.

Posting here as update, I'll research about those topics and make the fixes next Wednesday.

**Comment by Dubbled** [comment]
The way I've done it with ```host_timescale 0``` is by recording just the frames first and then going back with ```host_timescale 1``` and using ```host_framerate 0``` to capture the audio and video. Then when I use VD, I just enter in the FPS manually and sync the audio in Vegas to the clip.

**Comment by Dubbled** [comment]
Ok, so I've attempted to record using the version you posted on the 31st, and it seems there is a problem with the recording config. Once the frames have been rendered and the wav recorded, the wav sound is glitched as if ```host_timescale``` is set to ```0``` instead of ```1```, but this is not the case as I have attempted to change to ```host_timescale 1``` and this has not resolved the problem.

**Comment by iabarca** [comment]
Alright, but the config in that exact version was updated. Can you check updating that version to latest one (``4.2.0-pre.2-37``)

If you already did, files loaded into csgo are these: https://github.com/iabarca/lawena-recording-tool/tree/v4.x/lwrt/csgo/config/cfg

In particular, ``recording.cfg`` has the recording stuff. I've noticed that almost all of the commands there are not working due to being "locked" (says unknown command).

I'm going to change ``host_timescale`` to ``demo_timescale``: https://github.com/iabarca/lawena-recording-tool/blob/v4.x/lwrt/csgo/config/cfg/recbindings.cfg#L64

Also defaulting ``host_timescale`` to 0

That might solve it. Thanks

**Comment by iabarca** [comment]
Updated to ``4.2.0-pre.2-42`` of snapshot branch, reflecting above changes.

**Comment by Dubbled** [comment]
Ok, ```4.2.0-pre.2-42``` has solved the no audio problem. I was able to record with ```host_timescale 1``` and have no demo bugs.  Here is a 60 fps H.264 render.

https://www.youtube.com/watch?v=kXWIu3WdgdU

**Comment by Dubbled** [comment]
OK! I've done some more testing after a little bit of a hiatus and I've decided a couple of things should be changed to make the tool easier to use:

* The game should always launch with the default of ```host_framerate 0```. This makes navigating the demo to the point where you want to start your recording much easier. Once the start recording binding is pressed, the bind should automatically run the command ```host_framerate x``` where ```x``` is the selected recording framerate in the tool, and then begin recording.
* The start recording binding (default ```P```) should only record tga files. See next bullet point for an explanation.
* Since the demo sounds seem bugged in GO even with ```host_timescale .001```, there should be another bind (maybe ```[``` would work) that would record audio only with ```host_timescale 1```, ```host_framerate 0``` and ```startmovie x wav```. The user could then sync the audio to the clip manually until a better solution is found.

**Comment by iabarca** [comment]
Awesome, glad to have you back.

The suggestions are great but I'm not sure if ``startmovie`` can be used to do video-only or audio-only passes. I know that if you ignore the video and audio parameter, it just uses tga/wav by default. Have you confirmed that ``startmovie x wav`` works?

At the moment, the only way I know to avoid wasting disk space by doing two passes would be using [SrcDemo2](https://code.google.com/p/srcdemo2/).

**Comment by Dubbled** [comment]
I have confirmed that you can use ```startmovie x wav```. Run just ```startmovie``` and check out the output to look at the other options. We can also use ```startmovie x tga``` to do video only.

**Comment by iabarca** [comment]
Perfect. I'll be adapting the record bindings to allow for video-only and audio-only segments. Thanks

**Comment by iabarca** [comment]
Okay, pushed a couple commits, latest version is now ``4.2.0-pre.2-57``. It should allow recording of video only and audio only segments using F1 and F2 respectively. (0999d52)

Also added a way to remember game selection to avoid choosing game each time.

**Comment by Dubbled** [comment]
Sounds good. Two things:

* When recording audio, the ```host_framerate``` cvar automatically changes to the selected framerate in the tool. This should stay zero so the audio records at real time.
* The Skybox option can be re enabled. [Here](https://developer.valvesoftware.com/wiki/Counter-Strike:_Global_Offensive_Sky_List) is the skybox list for CS:GO. The command ```sv_skyname``` can change the sky in the demo. Not sure how you would want to implement this. The skybox will not change in the demo if the command is run at game launch. Instead maybe the skybox command could be run when recording with ```P``` or with ```F1```. I do not think there is a way to run a cfg at demo start.

**Comment by iabarca** [comment]
- Fixed and pushed.
- CS:Go handles skyboxes differently. In TF2 you actually have to replace the files using the same name as the default ones, so that mechanism in the app won't be useful for Global Offensive. I could add a toggle bind to rotate through each skybox, but I would have to compile a name. Can you check if I'm missing some of them, since I'm sure not all of them are detailed in that website, since I've found out about ``vertigoblue_hdr``

``bind F4 toggle sv_skyname cs_baggage_skybox_ embassy italy jungle office sky_cs15_daylight01_hdr sky_cs15_daylight02_hdr sky_cs15_daylight03_hdr sky_cs15_daylight04_hdr sky_dust vietnam vertigoblue_hdr``

**Comment by Dubbled** [comment]
I believe the skybox issues could be sorted using the same method as the recording framerate. Since the TF2 and CS:GO functionality are separate (from what I understand) wouldn't it be possible to do `lines.add("sv_skyboxname " + skybox);`?

**Comment by Dubbled** [comment]
I'll clarify. If there is a specific skybox selected in the drop down, do ```lines.add("alias startrecording "demo_timescale 0.001; recframerate; bind P stoprecording; sv_skyboxname " + skybox");``` to recbindings.cfg. If the skybox is set to default, just leave out the skybox part.

**Comment by iabarca** [comment]
I thought you could change skyboxes during the demo playback. Is that correct?

**Comment by Dubbled** [comment]
You can.

**Comment by iabarca** [comment]
At the moment I think It's not practical to extract the official vpks to get the skybox files and show preview images for the user to select, since the selected skybox can be modified in-game using ``sv_skyname`` command (this is not possible in TF2). I think a toggle (or group of aliases) to rotate between all available skyboxes should be enough.

**Comment by iabarca** [comment]
I pushed something to cover the skybox changing. Therefore I'm closing this since the basic functionality is available.

Further improvements or fixes to the cs:go version are going to their respective issues.
